# Generated by Django 3.2.8 on 2021-10-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя сайта')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('link_to_site', models.URLField(verbose_name='Ссылка на сайт')),
                ('link_to_rep', models.URLField(verbose_name='Ссылка на репозиторий')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
    ]
