# Generated by Django 3.2.8 on 2021-10-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='login_on_pythonanywhere',
            field=models.CharField(default=1, max_length=150, verbose_name='Логин'),
            preserve_default=False,
        ),
    ]
